# This .yaml cofinguration file contains all variables used by the snakemake pipeline
# DO NOT CHANGE parameter names without changing it in Snakefile as well
# On the other hand, some parameter values have to be inevitably modifed
# **********************************************************************************************************************************

### 0. General workflow parameters
fastq_directory:
output_directory:
genome_directory:
genome_fasta:
gtf:
sjdbOverhang: 99
extra_param_index: ''
paired_end:
fastq_suffix: ".fastq.gz"
read_suffix: ['_R1', '_R2']


### 1. FASTQ trimming
cutadapt_trimm_options: ''
fw_adapter_sequence: "AGATCGGAAGAGC"
rv_adapter_sequence: "AGATCGGAAGAGC"


### 2. STAR mapping
n_parallel_samples: 1
readFilesCommand: 'zcat'
star_extra_options: ''

